// How the rep side of the portal works, for Ask 3C's prompt. Static text in
// the cached prefix: no per-rep data here. Written from the portal code;
// portalGuide.test.ts fails when a tab, menu item, form or form reason in the
// real config is missing from it, so update this when the portal changes.

export const PORTAL_GUIDE = `Portal guide (the 3C portal at 3cworldgroup.com/portal; on a phone, add it to the home screen and open it from that icon):
- Tabs along the bottom: Home, Sales, Log sale (the big + button), Board, Chat. Top bar: the bell (notifications), Menu, and the rep's name (Settings, Report a bug, Sign out). Menu lists Calls, Forms, Learn, Ask 3C, and My Onboarding for new hires still onboarding, plus Settings and Sign out.
- Home: estimated pay this month, the This week card (Board rank and the weekly challenge; the week runs Sunday to Saturday, Central), a Today card (today's calls with Join, and sales that need an install date or were missed, with Add date / Reschedule), and Recent sales. Tapping a sale opens it.
- Log sale: log every T-Fiber sale as soon as you can (the next morning is fine, sooner is better). Step 1, Proof: Choose screenshot (the whole order confirmation, up to 4 screenshots) or Enter manually. The screenshot fills in order number, customer name, phone, address, install date and plan; "Check this" marks a field it wasn't sure of, so check everything before Submit sale. Step 2, Details: Provider, Plan, Order number or BTN (needed only without a screenshot), Customer name, Phone, Service address, Install date. More details holds email, sale type, sale date (the day the customer signed up, not the install day; never in the future) and notes. If it says the sale was already logged, tap View it instead of logging it twice. With no signal the entry is saved; tap Submit again. A logged sale shows on Sales right away and counts on the Board.
- Sales: every sale by month (the arrows change the month), with status lines: Installed <date>, Installs <date>, Needs install date, Missed install (reschedule), Cancelled. A carrier chip shows what the carrier's daily report says. Tap a sale for detail; Change sets or reschedules the install date (only on your own sale, not before the sale date, and a reschedule must be after the missed day). When the carrier's report moves a date, the sale updates on its own. Reps can't edit other details or cancel a sale; ask Jeremy or Jacob. The Pay view and How pay works are there too; pay there is always an estimate until 3C pays.
- Board: the leaderboard. Week, Month, Year or All time; ranked by Points or Sales (Week and Points by default). Week resets Sunday, Month on the 1st. Top 3 on the podium, then everyone else, and a Recent sales feed.
- Chat: team channels only (All Company, New Reps, Training Updates, Managers for managers). No private messages. Photos can be attached. Keep customer details out of chat.
- Calls: the weekly team call schedule, in Central time. Next call on top, a day picker for the week, Join opens Google Meet. Managers-only calls don't show for reps.
- Forms (send a request to the office; after sending you get a reference number, and the office marks it handled):
  Payroll dispute: an install missing from your pay or paid wrong. Contractor name and email, campaign, type of order, date of install, and a screenshot or proof.
  Expedite order: customer name, phone, order number, the dates you want, and a reason: Install too far out; Tech missed install need install asap; Customer no showed need it rescheduled asap.
  Fiber report: log a lead pack's door knocking and fiber sales (date knocked, pack number, doors, contacts, sales).
  Leads request: ask for a lead pack or flag a territory problem (campaign, manager, location; Jacob approves). Reasons: New rep neads logins and leads assigned; Terrtory has been worked and knocked multiple times with 2-3 knock dispositions; Hostile situation happened a the territory, requesting switch; another rep was caught knocking in our reps territory.
  Manager interview: managers only.
- Learn: Pay & links (your training progress, field tools like the TFiber Service Check, short videos, pay structure) and Training (modules and short videos).
- Ask 3C: this chat. Add a photo of an order screen or error. 60 questions a day. New chat starts over.
- Notifications: the bell shows install-tomorrow reminders, install date changes, missed installs, carrier cancellations and disconnects, and onboarding updates. Phone push: on iPhone, first add the portal to the home screen (Safari, Share, Add to Home Screen) and open it from that icon; then tap Turn on (the Home banner or Settings, Push notifications). If it still doesn't come through, check the phone's Settings, Notifications for the portal icon.
- Settings: your profile (display name, phone, shirt size; other details come from the office), push notifications, install the app, theme, Change password, and Report a bug.
- Sign in: email and password or Continue with Google. Forgot password? emails a reset link. New reps with a team code use Create your account, verify their email, then wait for their manager to activate them; invited hires use Finish your onboarding. My Onboarding is the new-hire checklist: upload or e-sign each item and submit it for review.
- Owners and admins also have People, Onboarding, Requests, Announcements and Admin settings; reps don't see those.`;
