// How the rep side of the portal works, for Ask 3C's prompt. Static text in
// the cached prefix: no per-rep data here. Written from the portal code;
// portalGuide.test.ts fails when a tab, menu item, form or form reason in the
// real config is missing from it, so update this when the portal changes.

export const PORTAL_GUIDE = `Portal guide (the 3C portal at 3cworldgroup.com/portal; on a phone, add it to the home screen and open it from that icon):
- Tabs along the bottom: Home, Sales, Log sale (the big + button), Board, Chat. Top bar: the bell (notifications), Menu, and the rep's name (Settings, Report a bug, Sign out). Menu lists Calls, Forms, Learn, Ask 3C, and My Onboarding for new hires still onboarding, plus Settings and Sign out.
- Home: estimated pay this month, the This week card (Board rank and the weekly challenge; the week runs Sunday to Saturday, Central), a Today card (today's calls with Join, and sales that need an install date or were missed, with Add date / Reschedule), and Recent sales. Tapping a sale opens it.
- Log sale: log every T-Fiber sale as soon as you can (the next morning is fine, sooner is better). Step 1, Proof: Choose screenshot (the whole order confirmation, up to 4 screenshots) or Enter manually. The screenshot fills in order number, customer name, phone, address, install date and plan; "Check this" marks a field it wasn't sure of, so check everything before Submit sale. Step 2, Details: Provider, Plan, Order number or BTN (needed only without a screenshot), Customer name, Phone, Service address, Install date. More details holds email, sale type, sale date (the day the customer signed up, not the install day; never in the future) and notes. If it says the sale was already logged, tap View it instead of logging it twice. With no signal the entry is saved; tap Submit again. A logged sale shows on Sales right away and counts on the Board.
- Sales: every sale by month (the arrows change the month), with status lines: Installed <date>, Installs <date>, Needs install date, Missed install (reschedule), Cancelled. A carrier chip shows what the carrier's daily report says. Tap a sale for detail; Change records the install date in the portal (only on your own sale, not before the sale date, and a reschedule must be after the missed day). Change only updates the portal; it does not book or move anything with T-Mobile (the customer calls 1-844-783-4237, or send the Expedite order form to the office). There is no search. When the carrier's report moves a date, the sale updates on its own. Reps can't edit other details or cancel a sale; ask Jeremy or Jacob. The Pay view and How pay works are there too; pay there is always an estimate until 3C pays. The pay schedule (installed the 1st-7th pays about the 14th-18th; 8th-14th about the 21st-25th; 15th-21st about the 28th-3rd of next month; 22nd-end of month about the 7th-11th of next month; always a range; missed installs settle by the 25th of next month; chargeback if cancelled within 120 days) is the How pay works button: on Sales under the pay card, on Home under the pay, and in Menu, Learn, Pay & links.
- Board: the leaderboard. Week, Month, Year or All time; ranked by Points or Sales (Week and Points by default). Week resets Sunday, Month on the 1st. Top 3 on the podium, then everyone else, and a Recent sales feed. The Board has no arrows to earlier weeks or months.
- Chat: team channels only (All Company, New Reps, Training Updates, Managers for managers). No private messages. Photos can be attached. No @mentions or tagging. Keep customer details out of chat.
- Calls: the weekly team call schedule, in Central time. Next call on top, a day picker for the week, Join opens Google Meet (no dial-in). Managers-only calls don't show for reps.
- Forms (five in all: Payroll dispute, Expedite order, Fiber report, Leads request, and Manager interview for managers; send a request to the office; after sending you get a reference number, and the office marks it handled):
  Payroll dispute: an install missing from your pay or paid wrong. Contractor name and email, campaign, type of order, date of install, and a screenshot or proof.
  Expedite order: customer name, phone, order number, the dates you want, and a reason: Install too far out; Tech missed install need install asap; Customer no showed need it rescheduled asap.
  Fiber report: log a lead pack's door knocking and fiber sales (date knocked, pack number, doors, contacts, sales).
  Leads request: ask for a lead pack or flag a territory problem (campaign, manager, location; Jacob approves). Reasons: New rep needs logins and leads assigned; Territory has been worked and knocked multiple times with 2-3 knock dispositions; Hostile situation happened at the territory, requesting switch; Another rep was caught knocking in our rep's territory.
  Manager interview: managers only.
- Learn: Pay & links (your training progress, field tools like the TFiber Service Check, pay structure) and Training (My training for modules; short videos are under Learn, Training, Short videos).
- Ask 3C: this chat. Add a photo of an order screen or error. 60 questions a day. New chat starts over. Practice is only for people it's turned on for: they see Ask and Practice buttons at the top of Ask 3C, and Practice lets them pitch a pretend homeowner at the door (typed, or out loud with Talk on) and get coached on it. Someone without those buttons doesn't have Practice yet; never promise it to them.
- Notifications: the bell shows install-tomorrow reminders, install date changes, missed installs, carrier cancellations and disconnects, and onboarding updates. Phone push: on iPhone, first add the portal to the home screen (Safari, Share, Add to Home Screen) and open it from that icon; then tap Turn on (the Home banner or Settings, Push notifications). If it still doesn't come through, check the phone's Settings, Notifications for the portal icon.
- Settings: your profile (display name, phone, shirt size; other details come from the office), push notifications, install the app, theme, Change password, and Report a bug.
- Sign in: email and password or Continue with Google. Forgot password? emails a reset link. New reps with a team code use Create your account, verify their email, then wait for their manager to activate them; invited hires use Finish your onboarding. My Onboarding is the new-hire checklist: upload or e-sign each item and submit it for review.
- Owners and admins also have an Admin group in the Menu (reps don't see it):
  People: Everyone (every user, tap one for their profile and to reveal SSN/DL#), Employee data, and Knowledge (owner only: Notes are what Ask 3C knows, add or edit them there; Questions shows every Ask 3C question and answer with thumbs up/down).
  Onboarding: Review (each new hire's checklist; tap a person, then an item; View files opens uploaded photos like the driver's license), Invites (the Recruiting page: send invites, which email the hire from the onboarding department; each open invite has Copy link and Resend email), Applicants (everyone who applied on the site with New/Invited/Onboarded filters, search, export, and an Invite button), Pipeline.
  Requests: the forms reps sent (payroll disputes, expedite orders, leads requests, fiber reports, manager interviews, bug reports).
  Announcements (send a message to reps) and Admin settings (form options, chat channels, email templates, University content, and Pay rates, owner only).`;
